### ISSUE TITLE
extract-between method

### ISSUE THREAD

**Issue by podviaznikov** [funcool/cuerdas#10]
Hi,
do you think method like this would be useful?

```
(defn extract-between [s prefix suffix]
  (some-> s
      (str/split prefix)
      second
      (str/split suffix)
      first))
```

**Comment by niwinz** [comment]
Sure! Can yo make a PR please?

**Comment by podviaznikov** [comment]
sure. will do. wanted to check with you first

**Comment by podviaznikov** [comment]
how to run tests locally?

**Comment by niwinz** [comment]
```
lein cljx once
lein cljsbuild test # for cljs
lein test  # for clj
```

**Comment by niwinz** [comment]
The tests are written using cljx, with new clojure release I will reweite them with reader conditionals :D

**Comment by podviaznikov** [comment]
reader conditionals are perfect for sure for cuerdas
