### ISSUE TITLE
Why goog.string/startsWith and Java .startsWith are not used?

### ISSUE THREAD

**Issue by PetrGlad** [funcool/cuerdas#14]
This is more a question rather than issue.
I see that some functions like starts-with? have custom implementation instead of using ones from available libraries.  E.g. java.lang.String has startsWith method, and google.string has startsWith also.
Is there a reason for this?

**Comment by niwinz** [comment]
Just for performance reasons.

In any case, if you thinking that some existing implementation is better that the current one, just purpose a change and it will be gladly merged! ;)

**Comment by PetrGlad** [comment]
`str.lastIndexOf(prefix, 0) == 0;` indeed does not look efficient (might not be actually slow in most cases though). 
Just found out that .startsWith is not supported everywhere... OK.

**Comment by PetrGlad** [comment]
startsWith, endsWith: Just looked at Java's implementation - I doubt one can beat that in Clojure.
Clojurescript implementation is the same as in goog.string
