### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by atstp** [funcool/cuerdas#23]
String interpolation, or even plain old key lookup, in `cuerdas`, would be great.  

There's a super capable [string interpolation macro](https://github.com/clojure/core.incubator/blob/98672b9f627631215b47744fe193550f389d1095/src/main/clojure/clojure/core/strint.clj) in the Clojure incubator, but it's been there for going on 7 years.

Thoughts on this, or something similar, in `cuerdas`?

**Comment by niwinz** [comment]
PR welcome, but should be licensed under BSD license, the implementation from incubator can't be used as is because it is licensed under EPL.

PR very welcome

**Comment by atstp** [comment]
great to hear!  i'm on it.

**Comment by emlyn** [comment]
Have you asked @cemerick if he's able/willing to relicense the incubator version under BSD?

**Comment by niwinz** [comment]
@emlyn indeed is an option, yes.

**Comment by cemerick** [comment]
Sounds good to me. I've created a gist of the `strint` namespace based on the last rev that is solely my work (from https://github.com/clojure/core.incubator/blob/9f2590f2cf22c37ba66010983bf6eaf21a90084c/src/main/clojure/clojure/core/strint.clj), and BSD-licensed. It could use a couple of type hints; otherwise, it's complete w.r.t. core.incubator master.

https://gist.github.com/cemerick/116c56b9504152d59d3e60fff6d57ea7

Feel free to adapt this for use here, or where ever. Of course, please do keep the attribution, etc. intact.

Nice that this will find a more well-trafficked home! :-)

**Comment by niwinz** [comment]
@cemerick awesome! This will be a very nice stuff to include for the next cuerdas release ;)

Many thanks!

@atstp I'm going to do it myself, so I assign this issue to me ;)

**Comment by niwinz** [comment]
I have renamed the `<<` to `fmt`. That do you thing about this? 

The `<<` is already used and rename it to `<<<` will make it more confusing with `<<`, and `fmt` is more clear in my opinion.

**Comment by niwinz** [comment]
Merged and bump the `1.0.0-SNAPSHOT` with it ;)

**Comment by cemerick** [comment]
IMO, `fmt` is not a great alternative; the macro isn't doing any formatting of the data being interpolated, which is a big distinction between it and things like `format`, `printf`, and so on.

The original inspiration syntactically were [heredocs](https://en.wikipedia.org/wiki/Here_document), thus the `<<`. Similar terms that capture that intent might be `interpolate`, `splice`, `template`, or similar.

ofc, you can call it anything you like, but you asked for opinions. ;-P

**Comment by niwinz** [comment]
@cemerick thanks for the feedback, the 1.0.0 is not released and we are on time to change it. And I'm very open to other alternatives.

The unique point is that I want a short and concise name for it. Maybe the solution passes to rename the current `<<` function to something different and keep `<<` for the string interpolation.

**Comment by niwinz** [comment]
On the end i have replaced `<<` with `<<-` in the same way as heredoc has, and rename `fmt` to `<<` as the original name also inspired from heredoc.

`fmt` now becomes a simple alias to `format` function. 

I think now it is more consistent and more concise naming ;)
