### ISSUE TITLE
unindenting heredoc/multiline strings

### ISSUE THREAD

**Issue by atstp** [funcool/cuerdas#24]
Multiline strings can be pretty nasty if they're meant to be user facing; multi-line strings are either ugly in code or ugly printed.

Currently, for a compromise, you'd either pass it through a `(re-)replace`, trimming the lines, or join a bunch of vectors with newlines (`cuerdas.core/unlines` :tada:).

Something like `multiline` would be great: It would take the the shortest newline-to-non-whitespace and trim that from every line.

as code, this

```
(cuerdas.core/multiline "this is an example
                         
                        of what to expect with
                        a `multiline` function"
```
would return the string:
```
this is an example
 
of what to expect with
a `multiline` function
```

Would this be a good fit for cuerdas?

This library's gotten me oddly excited about strings. Thanks for bearing with all the issues i've posted!

**Comment by niwinz** [comment]
I really like the functionallity but I don't like the multiline as function name, I think it should be something more shorter and more auto explained...

**Comment by atstp** [comment]
bash uses [`<<-`](http://tldp.org/LDP/abs/html/here-docs.html#EX71A) to strip tabs from heredocs

what about something like `<<auto`, and `<<custom`?  the `<<` characters give the appearance of moving the lines and it's reminiscent of bash's trimming heredoc.

  * `<<auto` would function as specified above
  * `<<custom` would accept a regex to trim?

`<<auto` seems like the only necessary one, but in the implementation, we'd be building `<<custom` for internal use, so there's no harm in exposing it.

**Comment by niwinz** [comment]
`<<` seems like a proper and commonly known name for that stuff.

**Comment by atstp** [comment]
okay, sounds good.  

what do you think about exposing two functions for this?  

It sounds like a simple `<<` is good for automatic unindenting, would an `<<unindent` function be okay to take a regex/string to trim?

**Comment by niwinz** [comment]
On the end I have renamed this function to be `<<-` in the same way as in heredoc.
