### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by emlyn** [funcool/cuerdas#26]
A couple of issues I found in the documentation:
- The list of functions is unsorted, making it hard to find anything
- The examples for `words` are incorrect (some of them are for `lines`)
- The "only clojure(script)" warnings are not clear if they apply to the preceding or the following function

**Comment by atstp** [comment]
I'm changing/renaming a good chunk of stuff for #21, so i'll take care of the alphabetical ordering when i'm wrapping up that rewrite.

In reference to the "only for" warnings, #20 should get rid of them entirely when it's closed &mdash; on the off-chance that any are outstanding, i'll clear them up.

**Comment by atstp** [comment]
This should be closable now; all three issues are taken care of.
