### ISSUE TITLE
Type hint return types

### ISSUE THREAD

**Issue by emlyn** [funcool/cuerdas#27]
When porting a project from `clojure.string` to `cuerdas`, I received a number of reflection warnings, due to the fact that the cuerdas functions do not have type hinting on the return values, where the equivalent clojure.string version does.
E.g. `curedas.core/lower` vs [`clojure.string/lower-case`](https://github.com/clojure/clojure/blob/36bebcd2ecd2a9a89e60c24c7cab533a8d4d6be2/src/clj/clojure/string.clj#L213).

**Comment by niwinz** [comment]
This is mainly because clojure and clojurescript has different ways to specify type hints, and having return value type hints will make write always two versions of the function.

**Comment by emlyn** [comment]
Oh that's annoying. Wouldn't something like `(defn #?(:clj ^String lower :cljs lower) ...)` be possible? Although even if so, it makes the code very ugly.

**Comment by niwinz** [comment]
In clojure, the valid type hint position is before argsvec, and in clojurescript before var symbol.

**Comment by emlyn** [comment]
Is that the case? In the `clojure.string` source (linked above) it is before the symbol.

**Comment by niwinz** [comment]
Yes, this is inconsistent, please read this mail thread https://groups.google.com/forum/#!msg/clojure/9ZmaZI6NO1I/99XTvn9kAgAJ 

and the documentation: http://clojure.org/reference/java_interop#typehints

**Comment by emlyn** [comment]
Although the documentation seems to say it should go on the arg vec, that thread seems to say it can go on either:
> If your type hint is a non primitive class, you want to put it in the Var or in the arglist as a fully qualified symbol

In which case couldn't you just put it on the var (even without any conditional and it would just be ignored in cljs)?

**Comment by niwinz** [comment]
Maybe, but I'm not pretty sure.

**Comment by niwinz** [comment]
I'll take care of this and put some type hints when I can, so I keep this issue open.

**Comment by emlyn** [comment]
Cool, thanks!

**Comment by niwinz** [comment]
Some work is done, but not all is posible. I consider this issue as closed. If you think that one concrete case can be improved, just open an issue for that concrete case.

Thanks.
