### ISSUE TITLE
converting between strings and keywords

### ISSUE THREAD

**Issue by atstp** [funcool/cuerdas#32]
I've been working with a bunch of semi-structured data recently and frequently need to convert between clojure keywords, humanized tsv/csv headers, and camelized json keywords, depending on the data's source and heading.   

What do you think about making the `<style>ize`ing functions (`humanize`, `captialize`, `camelize`, etc) keyword-safe by adding `clojure.core/name` to their `some->` threads?

`cuerdas.core/keyword` would be the counterpart, `dasherize`ing any strings before passing them to `clojure.core/keyword`.  

I'll be writing this code anyway, so if you think it would fit in cuerdas, i'd happily write it here!

**Comment by niwinz** [comment]
+1 please, the current versions are only work with strings but if you make them keyword safe, :+1:

**Comment by niwinz** [comment]
Covered by #33
