### ISSUE TITLE
(str/collapse-whitespace nil) causes NPE

### ISSUE THREAD

**Issue by podviaznikov** [funcool/cuerdas#4]
```
java.lang.NullPointerException: null
            string.clj:99 clojure.string/replace
             core.clj:100 cuerdas.core/replace
             core.clj:338 cuerdas.core/collapse-whitespace
```
But `(str/trim nil)` returns `nil`.

**Comment by niwibe** [comment]
This is already fixed in master and will be available in next version.

You can see the test here: https://github.com/funcool/cuerdas/blob/master/spec/cuerdas/core_spec.cljx#L29

**Comment by podviaznikov** [comment]
Perfect!
