### ISSUE TITLE
 `locale-caseless=` on clj (tries) to use the cljs interop `toLocaleLowerCase`

### ISSUE THREAD

**Issue by christoph-frick** [funcool/cuerdas#40]
user=> (str/locale-caseless= "hello" "HELLO")

	IllegalArgumentException No matching field found: toLocaleLowerCase for class java.lang.String  clojure.lang.Reflector.getInstanceField (Reflector.java:271)

Same problem with the upper/lowercase fns

**Comment by niwinz** [comment]
Thanks!

**Comment by niwinz** [comment]
Released 2.0.0-SNAPSHOT with that changes.
