### ISSUE TITLE
numeric? returns vector of matched regex(es), not a boolean

### ISSUE THREAD

**Issue by tuddman** [funcool/cuerdas#41]
ref: https://github.com/funcool/cuerdas/blob/master/src/cuerdas/core.cljc#L215

convention of fnName?  is to return `true | false`

docs say:   _Checks if a string contains only numeric characters._

numeric? instead returns vector of regex matches.

also, doesn't currently handle commas `,`  or currencies, e.g. `$`

**Comment by niwinz** [comment]
Thanks! I will fix it ASAP. (right now i'm not available because of my weeding days).

**Comment by niwinz** [comment]
Fixed in 1.0.2
