### ISSUE TITLE
Underscored gone

### ISSUE THREAD

**Issue by tuhlmann** [funcool/cuerdas#42]
I just updated cuerdas to 1.0.1 and found that `underscored` is gone.

There's an alias from `underscore` (without the d) to `snake`, I guess that should have been `underscored` to `snake` ?

```
(def ^:deprecated underscore snake)
```

**Comment by niwinz** [comment]
You are completly right

**Comment by niwinz** [comment]
Released 2.0.0-SNAPSHOT with that changes.
