### ISSUE TITLE
`title` doesn't work as expected when string contains non-alphanumerics

### ISSUE THREAD

**Issue by lacarmen** [funcool/cuerdas#44]
```
(title "mini(s)")
=> "Mini S"
(title "mini's")
=> "Mini S"
(title "follow-up")
=> "Follow Up"
```

Perhaps `stylize-split` should only split on spaces when `s` is a string?

**Comment by niwinz** [comment]
Thanks @lacarmen !

I think that the last example you pasted is correct, because _cuerdas_ interprets `-` as word separation. And I with others I completely agree, and it need to be fixed. 

I'm traveling just now so I'll try to fix it on my first free time ;)
