### ISSUE TITLE
Is it possible for strip-tags to preserve new line?

### ISSUE THREAD

**Issue by podviaznikov** [funcool/cuerdas#5]
Do you know if it's possible for `strip-tags` to respect new line?

E.x. if there is `<br>` tag it should be converted to the `\n`?

**Comment by niwibe** [comment]
Currently not! But I will include it the next version  \o/

Thanks for the idea.

**Comment by niwibe** [comment]
Now implemented and commited in master. You can see the devel docs on how to use it: http://funcool.github.io/cuerdas/devel/#_strip_tags

**Comment by podviaznikov** [comment]
Thanks, looks good!
