### ISSUE TITLE
Namespace cuerdas.vendor.xregexp not found

### ISSUE THREAD

**Issue by kiemdoder** [funcool/cuerdas#54]
When I try to require [cuerdas.core :as str] I get the following error:
No such namespace: cuerdas.vendor.xregexp, could not locate cuerdas/vendor/xregexp.cljs, cuerdas/vendor/xregexp.cljc, or Closure namespace "cuerdas.vendor.xregexp" in file file:/home/z/.m2/repository/funcool/cuerdas/2.0.3/cuerdas-2.0.3.jar!/cuerdas/regexp.cljc

**Comment by niwinz** [comment]
Some test case to reproduce that?

**Comment by alexandergunnarson** [comment]
I'm getting this same error when trying to run Figwheel.
