### ISSUE TITLE
cljs support for istr

### ISSUE THREAD

**Issue by devth** [funcool/cuerdas#55]
Any plans to support istr in ClojureScript?

**Comment by devth** [comment]
Ok apparently it does work in ClojureScript. What I didn't realize is it requires a literal string at compile time.

For example:

```clojure
(let [value 1
       e "foo ~{value}"]
   (cstr/istr e))
```
returns `"e"`

but:
``` clojure
(let [value 1]
   (cstr/istr "foo ~{value}"))
```

returns `"foo 1"`.

**Comment by niwinz** [comment]
Yeah, this is a macro, and is evaluated at compile time in order to avoid runtime interpolation. This is expected behavior.

**Comment by devth** [comment]
Yep, understood.

It would be very useful to be able to eval at runtime too. Maybe worth having a separate function, e.g. `eval-istr`?

**Comment by niwinz** [comment]
But it will not help to cljs, because cljs can't eval expressiones on runtime (the browser cljs), so the eval-istr will not be complete and in fact very similar to `fmt` function.
