### ISSUE TITLE
String interpolation doesn't work with anonymous function literal % arguments

### ISSUE THREAD

**Issue by emlyn** [funcool/cuerdas#57]
E.g.:
```clojure
(require '[cuerdas.core :refer [istr]])

;; This works fine:
(let [f (fn [n] (istr "n=~{n}"))]
  (f 1))
;; => "n=1"

;; This should be equivalent, but doesn't work:
(let [f #(istr "n=~{%}")]
  (f 1))
;; => clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: % in this context
```
This seems to be because the `#()` form is expanded before `istr`, so it doesn't see the `%` inside the string and therefore doesn't convert it to the mangled form. Unfortunately I'm not sure there's much that can be done to fix this.

**Comment by niwinz** [comment]
That is expected, `istr` is a macro and it evaluates the string interpolation on the compilation time.

**Comment by emlyn** [comment]
Yeah, it's a shame though, it would be handy if it worked.

**Comment by niwinz** [comment]
Seems like this is not a `cuerdas` problem, because is the clojure parser that does not detects the `%` inside string. Let see some code:

```text
user=> (macroexpand '#(istr "n=~{%}"))
(fn* [] (istr "n=~{%}"))
user=> (macroexpand '#(istr "n=~{%}" %))
(fn* [p1__1418#] (istr "n=~{%}" p1__1418#))
```

You can see that if you use the `%` only inside the string, the expanded reader macro is results in a function with no argument.
