### ISSUE TITLE
(blank? nil) returns nil, not true.

### ISSUE THREAD

**Issue by decoursin** [funcool/cuerdas#64]
[The documenation](https://funcool.github.io/cuerdas/latest/#blank) says that `(blank? nil)` => true, but that's not what I'm getting, see below:

(showing other `blank?` examples to show that the `blank?` is working, just not for `nil` or maybe your documentation is wrong?)
```
nick> (blank? "  ")
true
nick> (blank? nil)
nil
nick> (blank? "foobr")
false
nick> (blank? "")
true
nick> (blank? "\n")
true
nick> (blank? "\n\t")
true
```

**Comment by niwinz** [comment]
The documentation is wrong, thanks for reporting it.

**Comment by niwinz** [comment]
Fixed on master.
