### ISSUE TITLE
format with numbers

### ISSUE THREAD

**Issue by martin-rdz** [funcool/cuerdas#72]
It seems that `cuerdas/format` does not support formatting number, whereas it works for 
`goog.string`:

```
(cuerdas/format "%.2f" 5.34531) =>  "%.2f"
(js/goog.string.format "%.2f" 5.34531) => "5.35"
```

Yet I dont't know clojurescript well enough to patch it myself - sorry.
Regards, martin

**Comment by niwinz** [comment]
Yeah, this is because it does not formats numbers. It just a "interpolation`. Maybe the name is confusing.  cuerdas/format is not analogous to `goog.string.format`.
