### ISSUE TITLE
Documentation CSS not found

### ISSUE THREAD

**Issue by joshkh** [funcool/cuerdas#79]
I'm fairly certain the docs used to have some CSS, whereas now it's barebones.
https://funcool.github.io/cuerdas/latest/

404: https://niwi.nz/_assets/asciidoctor-styles/simple-red-titles/stylesheet.css

![image](https://user-images.githubusercontent.com/4752532/72016020-d29a6280-325a-11ea-84ee-6a28e36f959b.png)

We love this library with no qualms about its functionality. Just pointing out a potential mishap.

**Comment by benzap** [comment]
Love this library as well, and i'm seeing the same thing since the last publication.

**Comment by niwinz** [comment]
moved to cljdoc, thanks!
