### ISSUE TITLE
clean method

### ISSUE THREAD

**Issue by podviaznikov** [funcool/cuerdas#8]
Was `clean` method changed recently?

```
   (str/clean "23.12.2014    10:09:19")
```
returns `23.12.2014    10:09:19` - spaces were not removed. I'm using `0.3.0`.

**Comment by niwibe** [comment]
Hi @podviaznikov 
Not, is not changed.
And as far as I know, is expected behavior. See the test: https://github.com/funcool/cuerdas/blob/master/spec/cuerdas/core_spec.cljx#L151

**Comment by podviaznikov** [comment]
sorry, actually the result is `23.12.2014    10:09:19` - with 5 whitespaces. That is why I thought that something changed.

**Comment by podviaznikov** [comment]
Ok. So seems like github markdown removes whitespaces. I do have 5 whitespaces between date and time.

**Comment by niwibe** [comment]
Uh, very strange. I'll try to reproduce it tomorrow at first time. Thank you very mucho for reporting that!

**Comment by podviaznikov** [comment]
Yeah, looks very strange. Especially because you do have test.
No problems, thanks for the library and quick replies!

**Comment by niwibe** [comment]
I have added test for it and everything works as expected :S both, in cljs and clj implementations ...

**Comment by podviaznikov** [comment]
let's close this then
