### ISSUE TITLE
`blank?` returns `false` when passed `nil` value

### ISSUE THREAD

**Issue by titonbarua** [funcool/cuerdas#83]
Is this the expected behavior? If so, it seems counterintuitive. Also, it differs from the `clojure.string/blank?` which returns `true` when `nil` is passed.

I was using cuerdas as a "mostly" compatible enhancement to `clojure.string` namespace. Perhaps I was wrong.

**Comment by niwinz** [comment]
This library from its origins, strictly works with strings, this means it does not understand nil as empty seq or empty string.
In fact, `nil` is `nil`, or in other words it is not a empty or blank string.

Probably all functions in cuerdas that receive nil will return nil (probably with few exceptions).

Being strict and does not treat `nil` as string in some predicates has its tradeoffs, but from my perspective I needed a library that works with strings. I don't want to have blank? validation return true when no string is provided per example. If I want to accept nil, I should probably do something like: `(or (nil? x) (str/blank? x))` (explicitly specifying that nil are allowed)

**Comment by titonbarua** [comment]
I totally agree with the decision of this library only focusing on string types. But, "nil punning" is a commonly used idiom in Clojure. There is a chance people will get confused, like me. After discovering this behavior (because of a test case not behaving as expected), I had to hunt down all use of `blank?` in a large code base and replace it with something like you suggested.

Anyway, I think it would have been better if this was documented somewhere.

**Comment by niwinz** [comment]
> Anyway, I think it would have been better if this was documented somewhere.

Sure, I will put a large warning on top of the documentation page. Thanks for the suggestion.

**Comment by niwinz** [comment]
An additional option can be adding a set of new predicates like `blank-or-nil?` (only the companions to predicates that makes sense). PR welcome for this.
