### ISSUE TITLE
(starts-with? "" "xxx") returns true

### ISSUE THREAD

**Issue by AndyCorlin** [funcool/cuerdas#85]
I found that:
`(starts-with? "" "xxx")` and `(end-with? "" "xxx")` both return true.

This was changed in "Minor code refactor", before that they returned false.
https://github.com/funcool/cuerdas/commit/4ff5b329556871590f3e4cfb4b7bdd062394d21f

Was the change intentional or is this a bug?

**Comment by niwinz** [comment]
looks like a bug

**Comment by AndyCorlin** [comment]
Thanks for confirming!

So how do we go about it, will you fix it or do you want me to make a pull request?

**Comment by niwinz** [comment]
An PR is welcome, if not, I will find some time to fix this, looks a regression.

**Comment by AndyCorlin** [comment]
Thanks for merging the PR! When do you plan the next release? /Anders

**Comment by AndyCorlin** [comment]
Hi @niwinz!  When do you plan the next release? /Anders

**Comment by niwinz** [comment]
Released a version in clojars ;)

**Comment by AndyCorlin** [comment]
Super, thanks, downloaded and it works!

Now I see it was released already the 14th, while I was monitoring the tags in GitHub where the release haven't yet appeared.
